### ISSUE TITLE
Logout should redirect user to the logout URL of the identity provider

### ISSUE THREAD

**Issue by deniger** [openmrs/openmrs-module-oauth2login#1]
Currently, if the user clicks on logout he's not logged out from the Identity provider. It means that if he goes back to OpenMRS he's automatically logged in again.

The Logout workflow process:
1 - Invalidate the user's OpenMRS Session
2 - Redirect the user to Identity provider logout page.
For the second step, the URL could be defined in the file oauth2. properties I guess

**Comment by mks-d** [comment]
Thanks @deniger!
