### ISSUE TITLE
Build Application

### ISSUE THREAD

**Issue by cesarpastor** [openmrs/openmrs-module-oauth2login#6]
Hi

Can you please indicate in the document on how to build this, also if possible please provide requirements or configuration to build this. I'm having trouble building the source code.

Thanks in advance

`Non-resolvable parent POM for org.openmrs.module:oauth2login:1.0.0-SNAPSHOT: Could not transfer artifact org.openmrs.maven.parents:maven-parent-openmrs-module:pom:1.1.1 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [openmrs-repo (http://mavenrepo.openmrs.org/nexus/content/repositories/public, default, releases+snapshots)] and 'parent.relativePath' points at wrong local POM @ org.openmrs.module:oauth2login:1.0.0-SNAPSHOT,`

**Comment by mks-d** [comment]
@cesarpastor this should work now, can you confirm?

Better ask your questions on https://talk.openmrs.org/
